### ISSUE TITLE
PlantCamodataset

### ISSUE THREAD

**Issue by gggg01hhhh** [lartpang/OVCamo#3]
Why are some images missing in the dataset?
![Snipaste_2024-10-24_11-17-00](https://github.com/user-attachments/assets/fea494f9-b65f-45d2-878f-324b115f04c6)

**Comment by gggg01hhhh** [comment]
Can you provide us with this complete data set?

**Comment by lartpang** [comment]
@gggg01hhhh 

Perhaps the original author adjusted the dataset. I've share the version I'm using in the [release](https://github.com/lartpang/OVCamo/releases/tag/dataset-v1.1).

**Comment by gggg01hhhh** [comment]
@lartpang thank you
